name: C/C++ CI

on:
  push:
#    branches: [ master ]
  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./setup.sh
    - name: make stun
      run: make
    - name: make tests
      working-directory: tests
      run: make
    - name: run stun as background process and run tests
      run: (./stun&); sleep 1; ./tests/test_stun
    - name: clang-format
      run: clang-format -i *.cpp
    - name: Archive stun log
      uses: actions/upload-artifact@v1
      with:
        name: stun_log
        path: log.txt
    - name: Archive test log
      uses: actions/upload-artifact@v1
      with:
        name: stun_tests_log
        path: tests/log.txt
