# workflows/lint.yml
#
# Lint with clang-format
# Lint STUN Server with clang-format.

name: "Lint with clang-format"

on:
    push:
        branches:
            - master
        paths-ignore:
            - "**/README.md"
    workflow_dispatch:

jobs:
    lint-main:
        name: Lint with clang-format
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Run clang-format
              run: |
                  clang-format -i *.cpp
                  cd tests
                  clang-format -i *.c *.h
                  cd ..

            - name: Check if Code is Linted
              run: |
                  git diff-index --quiet HEAD || (echo "To pass this check please lint the code with clang-format" && false)
