# workflows/lint.yml
#
# Lint with clang-format
# Lint STUN Server with clang-format.

name: "Clang-format"

on:
    pull_request:
        branches:
            - main
            - staging
            - dev
        paths-ignore:
            - "**/README.md"
    workflow_dispatch:

jobs:
    lint-main:
        name: Lint with clang-format
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout Git Repository
              uses: actions/checkout@v2

            - name: Run clang-format
              run: |
                  clang-format -i *.cpp
                  cd tests
                  clang-format -i *.c *.h
                  cd ..

            - name: Check if Code is Linted
              run: |
                  # Show diff in GitHub Actions logs
                  git diff HEAD --

                  # This will return an error if there is a non-empty diff
                  git diff-index --quiet HEAD --
